<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h5_End-To-End Test Account PROD Mailgun</name>
   <tag></tag>
   <elementGuidId>9720d784-d6a5-4e3d-8c7c-f18a5fc1ac06</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[3]/div/div[28]/button/h5</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h5</value>
      <webElementGuid>3281af54-4c45-46c4-8855-2bedaeb295fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiTypography-root MuiTypography-h5 css-126jt6x-MuiTypography-root</value>
      <webElementGuid>8c2039c4-c017-45f7-baba-04435b5b9805</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>active-card</value>
      <webElementGuid>870c2d2f-42c3-477d-ae39-92ba4b928d14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>End-To-End Test Account [PROD Mailgun]</value>
      <webElementGuid>129d03f9-c457-4f72-82a0-49ca3312b038</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;sc-fLcnxK gdSfro&quot;]/div[@class=&quot;MuiGrid-root MuiGrid-container MuiGrid-spacing-xs-2 css-mhc70k-MuiGrid-root&quot;]/div[@class=&quot;MuiGrid-root MuiGrid-item MuiGrid-grid-xs-12 MuiGrid-grid-md-4 css-1lj5egr-MuiGrid-root&quot;]/button[@class=&quot;sc-cjibBx aNVGp&quot;]/h5[@class=&quot;MuiTypography-root MuiTypography-h5 css-126jt6x-MuiTypography-root&quot;]</value>
      <webElementGuid>c4c2eb7a-7958-4380-b133-b847d9f23e7b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[3]/div/div[28]/button/h5</value>
      <webElementGuid>d47fbf22-98c8-4573-adb4-20c5cb1ff660</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[28]/button/h5</value>
      <webElementGuid>87f48947-79b9-4390-b295-9a9b031e1614</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h5[(text() = 'End-To-End Test Account [PROD Mailgun]' or . = 'End-To-End Test Account [PROD Mailgun]')]</value>
      <webElementGuid>fe6f9b0a-e8b9-440c-8c6f-d06a63be82fa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
