<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h5_End-To-End Test Account PROD Mailgun</name>
   <tag></tag>
   <elementGuidId>d74f13ad-eb5a-42aa-ad0a-14f886728289</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div[3]/div/div[28]/button/h5</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h5</value>
      <webElementGuid>f625057f-3cb4-4ab6-bd2f-e754aad51b6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiTypography-root MuiTypography-h5 css-126jt6x-MuiTypography-root</value>
      <webElementGuid>8be4aeaf-c423-4cfd-9c07-769942661882</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-testid</name>
      <type>Main</type>
      <value>active-card</value>
      <webElementGuid>669116bc-f2fd-4180-8ba2-6b7439ded81c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>End-To-End Test Account [PROD Mailgun]</value>
      <webElementGuid>2a27582d-96f4-4460-97e4-a8aa0a0df208</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[@class=&quot;sc-fLcnxK gdSfro&quot;]/div[@class=&quot;MuiGrid-root MuiGrid-container MuiGrid-spacing-xs-2 css-mhc70k-MuiGrid-root&quot;]/div[@class=&quot;MuiGrid-root MuiGrid-item MuiGrid-grid-xs-12 MuiGrid-grid-md-4 css-1lj5egr-MuiGrid-root&quot;]/button[@class=&quot;sc-cOxWqc iQRQmg&quot;]/h5[@class=&quot;MuiTypography-root MuiTypography-h5 css-126jt6x-MuiTypography-root&quot;]</value>
      <webElementGuid>48f89965-9163-4c60-b783-4dda006ed602</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div[3]/div/div[28]/button/h5</value>
      <webElementGuid>42e91697-358f-4d74-ace4-02a0413c4f08</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[28]/button/h5</value>
      <webElementGuid>d2692291-ead1-4f30-9880-dd77582427b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//h5[(text() = 'End-To-End Test Account [PROD Mailgun]' or . = 'End-To-End Test Account [PROD Mailgun]')]</value>
      <webElementGuid>5cba657a-3448-47ea-a3b8-baf4a6712329</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
