<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Subscribed</name>
   <tag></tag>
   <elementGuidId>0834ac32-a37a-46b1-9e12-e59d2333c918</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#MuiDropDown-option-0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//li[@id='MuiDropDown-option-0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>ca76d9c5-2832-4bf0-a657-a4ad380418fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>8625cd4b-b8c6-4479-9cf8-2d9479696774</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>981e6da4-d7f2-4af3-98f0-decff4c85267</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>MuiDropDown-option-0</value>
      <webElementGuid>26405d17-e81a-45e2-93be-19c77daae732</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-option-index</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>e45cc85a-c0e8-4c3f-982d-209c1eac3c73</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>b17a7dac-2187-4bd2-b5b4-76741acd0adf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>2ca1e2e1-6a9e-4751-ae01-32be3e6baf87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>MuiAutocomplete-option Mui-focused</value>
      <webElementGuid>ca7b2cd2-51d7-4cf4-bff5-8af965451ae1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Subscribed</value>
      <webElementGuid>de1cf617-bde3-4c75-9f10-10e8f802b377</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;MuiDropDown-option-0&quot;)</value>
      <webElementGuid>e56b0edc-1f84-4bbb-ad15-4c95c0904b03</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//li[@id='MuiDropDown-option-0']</value>
      <webElementGuid>9ba3b5b7-0f27-4a5a-b614-83663109ef7b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='MuiDropDown-listbox']/li</value>
      <webElementGuid>13200dad-e5b2-423a-9a27-6aa206a89b27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li</value>
      <webElementGuid>2eb1c87d-8687-4313-a5df-108740c4e01e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@id = 'MuiDropDown-option-0' and (text() = 'Subscribed' or . = 'Subscribed')]</value>
      <webElementGuid>5fe89a3b-5c51-44ae-bdf7-a89e633b5ecd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
